### PR TITLE
Update 686609cc9783_.py

### PR DESCRIPTION
**Pull request by ion9**
more of the same, doing a new install and it looks like some of the table names are the wrong case.

### CODE REVIEW

**Comment by SpeedProg** [comment]
could I ask what Database backend you are using?

**Comment by ion9** [comment]
i started with mysql community 5.7 and after that was acting odd i moved to MariaDB. the only odd thing i'm doing is disable innodb on the DBMS. i have all the edits i had to make to get a good install i'll push them all at once. it was two migraction files and a database resource file.

**Comment by SpeedProg** [comment]
Ah okay, yeah mariadb under linux makes case sensitive names while under windows(where I was developing most of the time) the names are case insensitive :(

**Comment by ion9** [comment]
To fix it is just three files that need an edit, I'll get a commit together for it. Please be kind it's my first time.

On September 20, 2017 2:24:24 PM EDT, SpeedProg <notifications@github.com> wrote:
>Ah okay, yeah mariadb under linux makes case sensitive names while
>under windows(where I was developing most of the time) the names are
>case insensitive :(
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SpeedProg/eve-inc-waitlist/pull/2#issuecomment-330938810

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SpeedProg** [comment]
I should probably look into making all table names lowercase tbh.

**Comment by SpeedProg** [comment]
okay, so apparently there where 3 tables that had camel case names, that I later changed to all lower case names. So the tables now should all be ALL lower case.
Adding a rename command into the migration would fail on case insensitive installations, I thereby decided to change the migration scripts to go full lowercase from the start.
ee61d278cbf35599f4fa08116a864263361144ef like this.
Btw, are your table names camel case now in your db for the 3 EveApiScope, SSOToken and TokenScope ?
Because that might or might not cause problems since they are defined all lowercase in the db script.

**Comment by SpeedProg** [comment]
Okay I think I fixed this, if it wouldn't be too much work for you I would like you to delete your db and try again with the new version https://github.com/SpeedProg/eve-inc-waitlist/releases/tag/v1.0.2 .
This should fix it and have all lowercase table names at the end, which is my goal :(

**Comment by ion9** [comment]
I think I can do that.

On September 20, 2017 3:16:44 PM EDT, SpeedProg <notifications@github.com> wrote:
>Okay I think I fixed this, if it wouldn't be too much work for you I
>would like you to delete your db and try again with the new version
>https://github.com/SpeedProg/eve-inc-waitlist/releases/tag/v1.0.2 .
>This should fix it and have all lowercase table names at the end, which
>is my goal :(
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SpeedProg/eve-inc-waitlist/pull/2#issuecomment-330953071

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ion9** [comment]
I tested the 1.0.2 code, it worked as expected. much nicer on linux. Thank you.

the only problem i found i have called out at https://github.com/SpeedProg/eve-inc-waitlist/issues/5

**Pull request closed without merging**
